import { Config } from './types';

export const config: Config = {
  site: {
    title: 'Create Next App',
    description: 'Generated by create next app',
  },
  registry: {
    path: 'src/__registry__/index.tsx',
    blockPath: 'src/registry/blocks',
  },
  //   navigation: [],
  navigation: {},
  categories: {
    auth: {
      title: 'Authentication',
      description: 'Authentication blocks',
      slug: 'auth',
    },
  },
};
