type Config = typeof config;

const config = {
  site: {
    title: 'Create Next App',
    description: 'Generated by create next app',
  },
  registry: {
    path: 'src/__registry__/index.tsx',
    blockPath: 'src/registry/blocks',
  },
  navigation: [],
};
