// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

// import * as React from "react"

export const Index: Record<string, any> = {
  default: {
    auth: {
      blocks: {
        'auth-simple-centered': {
          id: 'auth-simple-centered',
          name: 'auth-simple-centered',
          description: 'A simple centered authentication block',
        },
      },
    },
    hero: {},
  },
};
