// Path: src/__registry__/index.ts
// This file is generated by scripts/build-registry.ts
// Do not edit this file directly

type Registry = {
  id: string;
  label: string;
  collections: { id: string; label: string }[];
}[];
  
export const Index: Registry = [
  {
    id: 'application',
    label: 'Application',
    collections: [
      {
        id: 'dashboard',
        label: 'Dashboard'
      },
    ]
  },
  {
    id: 'e-commerce',
    label: 'E-Commerce',
    collections: [
      {
        id: 'product-list',
        label: 'Product List'
      },
    ]
  },
  {
    id: 'marketing',
    label: 'Marketing',
    collections: [
      {
        id: 'about',
        label: 'About'
      },
      {
        id: 'hero',
        label: 'Hero Blocks'
      },
      {
        id: 'logo-clouds',
        label: 'Logo clouds'
      },
      {
        id: 'stats',
        label: 'Stats'
      },
      {
        id: 'testimonials',
        label: 'Testimonials'
      },
    ]
  },
]