import { TWIndicator } from '@/components/tw-indicator';
import { Toaster } from '@/components/ui/sonner';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {children}
        <Toaster position="bottom-right" closeButton />
        <TWIndicator />
      </body>
    </html>
  );
}
