import fs from 'fs';
import path from 'path';

const registryPath = path.join(__dirname, '../src/__registry__/index.tsx');
const blockPath = path.join(__dirname, '../src/registry/blocks');

// ----------------------------------------------------------------------------
// Build __registry__/index.tsx.
// ----------------------------------------------------------------------------
let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
    "default": {    
`;

const resolvedBlocks = fs.readdirSync(blockPath);

for (const block of resolvedBlocks) {
  const blockName = block.split('.')[0];

  const codeValue = fs.readFileSync(`${blockPath}/${block}`, 'utf8');

  const code = codeValue.replace(/(?:\r\n|\r|\n)/g, '\\n');

  index += `        "${blockName}": {
            name: '${blockName}',
            component: React.lazy(() => import('@/registry/blocks/${block}')),
            files: ['registry/blocks/${block}.tsx'],
            code: \`${code}\`,
        },
`;
}

index += `
    }
}
`;

fs.writeFileSync(registryPath, index);

console.log('Registry built! ✅');

// ----------------------------------------------------------------------------
// TODO: Build /app/blocks/[block]/page.tsx
